CREATE TABLE IF NOT EXISTS ROLE(
    ID_ROLE SERIAL,
    ROLE VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID_ROLE),
    UNIQUE(ROLE)
);

CREATE TABLE IF NOT EXISTS TOKEN(
    ID_TOKEN SERIAL,
    TOKEN VARCHAR(255) NOT NULL,
    DATE_EXPIRATION TIMESTAMP NOT NULL,
    PRIMARY KEY(ID_TOKEN),
    UNIQUE(TOKEN)
);

CREATE TABLE IF NOT EXISTS PIN(
    ID_PIN SERIAL,
    PIN VARCHAR(255) NOT NULL,
    DATE_EXPIRATION TIMESTAMP NOT NULL,
    PRIMARY KEY(ID_PIN)
);

CREATE TABLE IF NOT EXISTS TENTATIVE_CONNECTION(
    ID_TENTATIVE_CONNECTION SERIAL,
    NOMBRE INTEGER NOT NULL,
    PRIMARY KEY(ID_TENTATIVE_CONNECTION)
);

CREATE TABLE IF NOT EXISTS UTILISATEUR(
    ID_UTILISATEUR SERIAL,
    PSEUDO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_TENTATIVE_CONNECTION INTEGER NOT NULL,
    ID_PIN INTEGER,
    ID_TOKEN INTEGER,
    ID_ROLE INTEGER NOT NULL,
    PRIMARY KEY(ID_UTILISATEUR),
    UNIQUE(ID_TENTATIVE_CONNECTION),
    UNIQUE(EMAIL),
    FOREIGN KEY(ID_TENTATIVE_CONNECTION) REFERENCES TENTATIVE_CONNECTION(ID_TENTATIVE_CONNECTION),
    FOREIGN KEY(ID_PIN) REFERENCES PIN(ID_PIN),
    FOREIGN KEY(ID_TOKEN) REFERENCES TOKEN(ID_TOKEN),
    FOREIGN KEY(ID_ROLE) REFERENCES ROLE(ID_ROLE)
);

INSERT INTO role (name) VALUES ('GUEST');